-- ============================================================================
-- Script: 02-grant-privileges.sql
-- Description: Grant required privileges to COMPRESSION_MGR user
-- Author: Daniel Moya (copyright), GitHub: github.com/danimoya Website: danielmoya.cv
-- Database: Oracle 23c Free Edition
-- ============================================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO ON
SET SERVEROUTPUT ON SIZE UNLIMITED

-- Connect to PDB
ALTER SESSION SET CONTAINER = FREEPDB1;

PROMPT ========================================
PROMPT Granting Privileges to COMPRESSION_MGR
PROMPT ========================================

-- Basic connection and resource privileges
GRANT CREATE SESSION TO COMPRESSION_MGR;
GRANT RESOURCE TO COMPRESSION_MGR;
GRANT CONNECT TO COMPRESSION_MGR;

PROMPT Basic privileges granted

-- Object creation privileges
GRANT CREATE TABLE TO COMPRESSION_MGR;
GRANT CREATE VIEW TO COMPRESSION_MGR;
GRANT CREATE PROCEDURE TO COMPRESSION_MGR;
GRANT CREATE SEQUENCE TO COMPRESSION_MGR;
GRANT CREATE TRIGGER TO COMPRESSION_MGR;
GRANT CREATE TYPE TO COMPRESSION_MGR;
GRANT CREATE MATERIALIZED VIEW TO COMPRESSION_MGR;
GRANT CREATE JOB TO COMPRESSION_MGR;

PROMPT Object creation privileges granted

-- Required for compression analysis
GRANT SELECT ON V_$DATABASE TO COMPRESSION_MGR;
GRANT SELECT ON V_$INSTANCE TO COMPRESSION_MGR;
GRANT SELECT ON V_$VERSION TO COMPRESSION_MGR;
GRANT SELECT ON DBA_TABLES TO COMPRESSION_MGR;
GRANT SELECT ON DBA_TAB_COLUMNS TO COMPRESSION_MGR;
GRANT SELECT ON DBA_SEGMENTS TO COMPRESSION_MGR;
GRANT SELECT ON DBA_TABLESPACES TO COMPRESSION_MGR;
GRANT SELECT ON DBA_DATA_FILES TO COMPRESSION_MGR;
GRANT SELECT ON DBA_FREE_SPACE TO COMPRESSION_MGR;
GRANT SELECT ON USER_SEGMENTS TO COMPRESSION_MGR;

PROMPT Data dictionary views granted

-- DBMS packages required for compression
GRANT EXECUTE ON DBMS_COMPRESSION TO COMPRESSION_MGR;
GRANT EXECUTE ON DBMS_STATS TO COMPRESSION_MGR;
GRANT EXECUTE ON DBMS_SPACE TO COMPRESSION_MGR;
GRANT EXECUTE ON DBMS_METADATA TO COMPRESSION_MGR;
GRANT EXECUTE ON DBMS_REDEFINITION TO COMPRESSION_MGR;
GRANT EXECUTE ON DBMS_OUTPUT TO COMPRESSION_MGR;
GRANT EXECUTE ON DBMS_SQL TO COMPRESSION_MGR;
GRANT EXECUTE ON DBMS_SCHEDULER TO COMPRESSION_MGR;
GRANT EXECUTE ON DBMS_LOCK TO COMPRESSION_MGR;
GRANT EXECUTE ON UTL_FILE TO COMPRESSION_MGR;

PROMPT DBMS package privileges granted

-- Additional system privileges for advanced features
GRANT SELECT ANY TABLE TO COMPRESSION_MGR;
GRANT ALTER ANY TABLE TO COMPRESSION_MGR;
GRANT ANALYZE ANY TO COMPRESSION_MGR;

PROMPT Advanced privileges granted

-- Grant privileges on SCRATCH tablespace (will be created in next script)
-- This will be done after tablespace creation

-- Create synonyms for easier access
CREATE OR REPLACE SYNONYM COMPRESSION_MGR.DBMS_COMPRESSION FOR SYS.DBMS_COMPRESSION;
CREATE OR REPLACE SYNONYM COMPRESSION_MGR.DBMS_STATS FOR SYS.DBMS_STATS;
CREATE OR REPLACE SYNONYM COMPRESSION_MGR.DBMS_SPACE FOR SYS.DBMS_SPACE;
CREATE OR REPLACE SYNONYM COMPRESSION_MGR.DBMS_METADATA FOR SYS.DBMS_METADATA;

PROMPT Synonyms created

-- Verify privileges
PROMPT Verifying privileges...
SELECT grantee, privilege, admin_option
FROM dba_sys_privs
WHERE grantee = 'COMPRESSION_MGR'
ORDER BY privilege;

PROMPT ========================================
PROMPT Privilege Grant Complete
PROMPT ========================================

EXIT;
