ALTER TABLE t_compression_history DROP CONSTRAINT CHK_HISTORY_OPERATION_STATUS;
ALTER TABLE t_compression_history ADD CONSTRAINT CHK_HISTORY_OPERATION_STATUS CHECK (
    OPERATION_STATUS IN ('QUEUED', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'ROLLED_BACK', 'PARTIAL_SUCCESS')
);
