/*******************************************************************************
 * HCC Compression Advisor - Schema Objects (Oracle 23c Free & Exadata)
 * Version: 1.0.0
 * Date: 2025-11-13
 *
 * DESCRIPTION:
 *   Production-ready schema for compression analysis and execution tracking.
 *   Platform-aware support: Standard compression for Oracle 23c Free,
 *   HCC (Hybrid Columnar Compression) for Oracle Exadata.
 *
 * SUPPORTED COMPRESSION TYPES (Oracle 23c Free):
 *   - BASIC (ROW STORE COMPRESS BASIC)
 *   - OLTP (ROW STORE COMPRESS ADVANCED)
 *   - ADV_LOW (COLUMN STORE COMPRESS FOR QUERY LOW - if licensed)
 *   - ADV_HIGH (COLUMN STORE COMPRESS FOR QUERY HIGH - if licensed)
 *
 * SUPPORTED COMPRESSION TYPES (Oracle Exadata - HCC):
 *   - QUERY LOW (HCC COMPRESS FOR QUERY LOW)
 *   - QUERY HIGH (HCC COMPRESS FOR QUERY HIGH)
 *   - ARCHIVE LOW (HCC COMPRESS FOR ARCHIVE LOW)
 *   - ARCHIVE HIGH (HCC COMPRESS FOR ARCHIVE HIGH)
 *
 * USAGE:
 *   Connect as schema owner (e.g., COMPRESSION_MGR) and execute:
 *   @01_schema.sql
 *
 * DEPENDENCIES:
 *   - Oracle Database 23c Free or higher
 *   - CREATE TABLE, SEQUENCE, INDEX privileges
 *
 ******************************************************************************/

SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 200
SET PAGESIZE 1000

PROMPT ================================================================================
PROMPT Creating HCC Compression Advisor Schema Objects (Oracle 23c Free)
PROMPT ================================================================================

-- ============================================================================
-- SECTION 1: STRATEGY CONFIGURATION TABLES
-- ============================================================================

PROMPT
PROMPT Creating strategy configuration tables...

-- ----------------------------------------------------------------------------
-- Table: T_COMPRESSION_STRATEGIES
-- Purpose: Define compression recommendation strategies and thresholds
-- ----------------------------------------------------------------------------
CREATE TABLE T_COMPRESSION_STRATEGIES (
    -- Primary Key
    STRATEGY_ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    -- Strategy Identification
    STRATEGY_NAME           VARCHAR2(50) NOT NULL,
    DESCRIPTION             VARCHAR2(500),
    CATEGORY                VARCHAR2(30) DEFAULT 'BALANCED',
    -- Threshold Parameters for Hotness Scoring
    HOTNESS_THRESHOLD_HOT   NUMBER DEFAULT 75,  -- >= 75 = HOT (minimal compression)
    HOTNESS_THRESHOLD_WARM  NUMBER DEFAULT 50,  -- 50-74 = WARM (OLTP compression)
    HOTNESS_THRESHOLD_COOL  NUMBER DEFAULT 25,  -- 25-49 = COOL (ADV_LOW compression)
                                                 -- < 25 = COLD (ADV_HIGH compression)
    -- DML Activity Thresholds (operations per day)
    DML_THRESHOLD_HIGH      NUMBER DEFAULT 10000,
    DML_THRESHOLD_MEDIUM    NUMBER DEFAULT 1000,
    DML_THRESHOLD_LOW       NUMBER DEFAULT 100,
    -- Size Thresholds (GB)
    SIZE_THRESHOLD_LARGE_GB NUMBER DEFAULT 50,
    SIZE_THRESHOLD_MEDIUM_GB NUMBER DEFAULT 10,
    SIZE_THRESHOLD_SMALL_GB NUMBER DEFAULT 1,
    -- Data Age Thresholds (days)
    AGE_THRESHOLD_RECENT_DAYS   NUMBER DEFAULT 30,
    AGE_THRESHOLD_OLD_DAYS      NUMBER DEFAULT 90,
    AGE_THRESHOLD_ARCHIVE_DAYS  NUMBER DEFAULT 180,
    -- Minimum Compression Requirements
    MIN_COMPRESSION_RATIO   NUMBER(4,2) DEFAULT 1.5,  -- Minimum 1.5:1 ratio
    MIN_SPACE_SAVINGS_MB    NUMBER DEFAULT 100,       -- Minimum 100MB savings
    -- Status and Metadata
    ACTIVE_FLAG             VARCHAR2(1) DEFAULT 'Y',
    IS_DEFAULT              VARCHAR2(1) DEFAULT 'N',
    PRIORITY                NUMBER DEFAULT 50,
    CREATED_DATE            DATE DEFAULT SYSDATE,
    CREATED_BY              VARCHAR2(128) DEFAULT USER,
    MODIFIED_DATE           DATE,
    MODIFIED_BY             VARCHAR2(128),
    -- Constraints
    CONSTRAINT PK_COMPRESSION_STRATEGIES PRIMARY KEY (STRATEGY_ID),
    CONSTRAINT UNQ_STRATEGY_NAME UNIQUE (STRATEGY_NAME),
    CONSTRAINT CHK_STRATEGY_ACTIVE CHECK (ACTIVE_FLAG IN ('Y', 'N')),
    CONSTRAINT CHK_STRATEGY_DEFAULT CHECK (IS_DEFAULT IN ('Y', 'N')),
    CONSTRAINT CHK_STRATEGY_CATEGORY CHECK (
        CATEGORY IN ('PERFORMANCE', 'BALANCED', 'SPACE', 'CUSTOM')
    ),
    CONSTRAINT CHK_MIN_RATIO CHECK (MIN_COMPRESSION_RATIO >= 1.0),
    CONSTRAINT CHK_HOTNESS_THRESHOLDS CHECK (
        HOTNESS_THRESHOLD_COOL < HOTNESS_THRESHOLD_WARM AND
        HOTNESS_THRESHOLD_WARM < HOTNESS_THRESHOLD_HOT
    )
);

COMMENT ON TABLE T_COMPRESSION_STRATEGIES IS 'Compression recommendation strategies and threshold configurations';
COMMENT ON COLUMN T_COMPRESSION_STRATEGIES.HOTNESS_THRESHOLD_HOT IS 'Score >= this value = HOT (minimal compression)';
COMMENT ON COLUMN T_COMPRESSION_STRATEGIES.HOTNESS_THRESHOLD_WARM IS 'Score >= this value = WARM (OLTP compression)';
COMMENT ON COLUMN T_COMPRESSION_STRATEGIES.HOTNESS_THRESHOLD_COOL IS 'Score >= this value = COOL (ADV_LOW compression)';

-- Ensure only one default strategy exists
CREATE UNIQUE INDEX UNQ_DEFAULT_STRATEGY ON T_COMPRESSION_STRATEGIES(
    CASE WHEN IS_DEFAULT = 'Y' THEN 'DEFAULT' END
);

-- ----------------------------------------------------------------------------
-- Table: T_STRATEGY_RULES
-- Purpose: Detailed rules for compression type selection by strategy
-- ----------------------------------------------------------------------------
CREATE TABLE T_STRATEGY_RULES (
    -- Primary Key
    RULE_ID                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    -- Foreign Key to Strategy
    STRATEGY_ID             NUMBER NOT NULL,
    -- Rule Definition
    OBJECT_TYPE             VARCHAR2(30) DEFAULT 'TABLE',  -- TABLE, INDEX, LOB, IOT
    HOTNESS_MIN             NUMBER DEFAULT 0,
    HOTNESS_MAX             NUMBER DEFAULT 100,
    DML_RATIO_THRESHOLD     NUMBER(5,2),  -- Write operations / Total operations
    -- Compression Recommendation
    COMPRESSION_TYPE        VARCHAR2(30) NOT NULL,
    -- Rule Priority and Status
    PRIORITY                NUMBER DEFAULT 50,
    ENABLED_FLAG            VARCHAR2(1) DEFAULT 'Y',
    RULE_DESCRIPTION        VARCHAR2(500),
    -- Constraints
    CONSTRAINT PK_STRATEGY_RULES PRIMARY KEY (RULE_ID),
    CONSTRAINT FK_RULE_STRATEGY FOREIGN KEY (STRATEGY_ID)
        REFERENCES T_COMPRESSION_STRATEGIES(STRATEGY_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_RULE_OBJECT_TYPE CHECK (
        OBJECT_TYPE IN ('TABLE', 'INDEX', 'LOB', 'IOT')
    ),
    CONSTRAINT CHK_RULE_COMPRESSION_TYPE CHECK (
        COMPRESSION_TYPE IN ('NONE', 'BASIC', 'OLTP', 'ADV_LOW', 'ADV_HIGH')
    ),
    CONSTRAINT CHK_RULE_ENABLED CHECK (ENABLED_FLAG IN ('Y', 'N')),
    CONSTRAINT CHK_HOTNESS_RANGE CHECK (
        HOTNESS_MIN >= 0 AND HOTNESS_MAX <= 100 AND HOTNESS_MIN <= HOTNESS_MAX
    )
);

COMMENT ON TABLE T_STRATEGY_RULES IS 'Detailed rules for compression type selection within each strategy';

CREATE INDEX IDX_STRATEGY_RULES_STRATEGY ON T_STRATEGY_RULES(STRATEGY_ID, PRIORITY DESC);

-- ============================================================================
-- SECTION 2: ANALYSIS RESULT TABLES
-- ============================================================================

PROMPT
PROMPT Creating analysis result tables...

-- ----------------------------------------------------------------------------
-- Table: T_COMPRESSION_ANALYSIS
-- Purpose: Primary table for table/IOT compression analysis results
-- ----------------------------------------------------------------------------
CREATE TABLE T_COMPRESSION_ANALYSIS (
    -- Primary Key
    ANALYSIS_ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    -- Object Identification
    OWNER                   VARCHAR2(128) NOT NULL,
    OBJECT_NAME             VARCHAR2(128) NOT NULL,
    OBJECT_TYPE             VARCHAR2(30) NOT NULL,  -- TABLE, IOT
    PARTITION_NAME          VARCHAR2(128),
    SUBPARTITION_NAME       VARCHAR2(128),
    -- Size and Row Metrics
    SIZE_BYTES              NUMBER,
    SIZE_MB                 NUMBER GENERATED ALWAYS AS (SIZE_BYTES/1024/1024) VIRTUAL,
    SIZE_GB                 NUMBER GENERATED ALWAYS AS (SIZE_BYTES/1024/1024/1024) VIRTUAL,
    ROW_COUNT               NUMBER,
    BLOCK_COUNT             NUMBER,
    AVG_ROW_LENGTH          NUMBER,
    -- Compression Ratios (Oracle 23c Free - No HCC)
    -- Ratio > 1 means compression is effective
    BASIC_RATIO             NUMBER(5,2),        -- COMPRESS BASIC
    OLTP_RATIO              NUMBER(5,2),        -- COMPRESS ADVANCED (OLTP)
    ADV_LOW_RATIO           NUMBER(5,2),        -- COMPRESS FOR QUERY LOW (if licensed)
    ADV_HIGH_RATIO          NUMBER(5,2),        -- COMPRESS FOR QUERY HIGH (if licensed)
    -- Block count details for ratio calculation
    BLKCNT_UNCMP_BASIC      NUMBER,
    BLKCNT_CMP_BASIC        NUMBER,
    BLKCNT_UNCMP_OLTP       NUMBER,
    BLKCNT_CMP_OLTP         NUMBER,
    BLKCNT_UNCMP_ADV_LOW    NUMBER,
    BLKCNT_CMP_ADV_LOW      NUMBER,
    BLKCNT_UNCMP_ADV_HIGH   NUMBER,
    BLKCNT_CMP_ADV_HIGH     NUMBER,
    BEST_RATIO              NUMBER(5,2) GENERATED ALWAYS AS (
        GREATEST(
            NVL(BASIC_RATIO, 0),
            NVL(OLTP_RATIO, 0),
            NVL(ADV_LOW_RATIO, 0),
            NVL(ADV_HIGH_RATIO, 0)
        )
    ) VIRTUAL,
    -- DML Activity Metrics (from ALL_TAB_MODIFICATIONS)
    INSERT_COUNT            NUMBER DEFAULT 0,
    UPDATE_COUNT            NUMBER DEFAULT 0,
    DELETE_COUNT            NUMBER DEFAULT 0,
    TOTAL_DML               NUMBER GENERATED ALWAYS AS (
        NVL(INSERT_COUNT, 0) + NVL(UPDATE_COUNT, 0) + NVL(DELETE_COUNT, 0)
    ) VIRTUAL,
    -- Access Pattern Metrics (from V$SEGMENT_STATISTICS)
    LOGICAL_READS           NUMBER,
    PHYSICAL_READS          NUMBER,
    ACCESS_FREQUENCY        NUMBER,  -- Combined read metric
    LAST_ACCESS_DATE        DATE,
    -- Hotness Score (0-100 scale)
    -- Formula considers: DML rate, access frequency, data age
    HOTNESS_SCORE           NUMBER(5,2),
    HOTNESS_CATEGORY        VARCHAR2(10) GENERATED ALWAYS AS (
        CASE
            WHEN HOTNESS_SCORE >= 75 THEN 'HOT'
            WHEN HOTNESS_SCORE >= 50 THEN 'WARM'
            WHEN HOTNESS_SCORE >= 25 THEN 'COOL'
            ELSE 'COLD'
        END
    ) VIRTUAL,
    -- Read/Write Ratios
    READ_RATIO              NUMBER(5,2),   -- Reads / Total Operations
    WRITE_RATIO             NUMBER(5,2),   -- Writes / Total Operations
    DML_24H_RATE            NUMBER,        -- DML operations per day
    -- Data Age
    LAST_ANALYZED           DATE,
    DATA_AGE_DAYS           NUMBER,
    -- Current Compression State
    CURRENT_COMPRESSION     VARCHAR2(30),
    COMPRESSION_ENABLED     VARCHAR2(1) GENERATED ALWAYS AS (
        CASE WHEN CURRENT_COMPRESSION IS NOT NULL THEN 'Y' ELSE 'N' END
    ) VIRTUAL,
    -- Recommendation
    ADVISABLE_COMPRESSION   VARCHAR2(30),
    RECOMMENDATION_REASON   VARCHAR2(4000),
    CONFIDENCE_SCORE        NUMBER(5,2),  -- 0-100 confidence level
    -- Space Savings Projection
    PROJECTED_SAVINGS_BYTES NUMBER,
    PROJECTED_SAVINGS_MB    NUMBER GENERATED ALWAYS AS (
        PROJECTED_SAVINGS_BYTES/1024/1024
    ) VIRTUAL,
    PROJECTED_SAVINGS_PCT   NUMBER(5,2),
    -- Analysis Metadata
    ADVISOR_RUN_ID          NUMBER NOT NULL,
    ANALYSIS_DATE           DATE DEFAULT SYSDATE,
    ANALYSIS_TIMESTAMP      TIMESTAMP DEFAULT SYSTIMESTAMP,
    ANALYSIS_DURATION_SEC   NUMBER,
    SAMPLE_SIZE_ROWS        NUMBER,
    -- Audit
    LAST_UPDATED            TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- Constraints
    CONSTRAINT PK_COMPRESSION_ANALYSIS PRIMARY KEY (ANALYSIS_ID),
    CONSTRAINT CHK_OBJECT_TYPE CHECK (
        OBJECT_TYPE IN ('TABLE', 'IOT', 'PARTITION', 'SUBPARTITION')
    ),
    CONSTRAINT CHK_ADVISABLE_COMPRESSION CHECK (
        ADVISABLE_COMPRESSION IN ('NONE', 'BASIC', 'OLTP', 'ADV_LOW', 'ADV_HIGH')
    ),
    CONSTRAINT CHK_HOTNESS_SCORE CHECK (
        HOTNESS_SCORE IS NULL OR (HOTNESS_SCORE BETWEEN 0 AND 100)
    ),
    CONSTRAINT CHK_CONFIDENCE_SCORE CHECK (
        CONFIDENCE_SCORE IS NULL OR (CONFIDENCE_SCORE BETWEEN 0 AND 100)
    ),
    CONSTRAINT CHK_COMPRESSION_RATIOS CHECK (
        (BASIC_RATIO IS NULL OR BASIC_RATIO >= 0.5) AND
        (OLTP_RATIO IS NULL OR OLTP_RATIO >= 0.5) AND
        (ADV_LOW_RATIO IS NULL OR ADV_LOW_RATIO >= 0.5) AND
        (ADV_HIGH_RATIO IS NULL OR ADV_HIGH_RATIO >= 0.5)
    )
);

COMMENT ON TABLE T_COMPRESSION_ANALYSIS IS 'Compression analysis results for tables and IOTs (Oracle 23c Free)';
COMMENT ON COLUMN T_COMPRESSION_ANALYSIS.BASIC_RATIO IS 'Compression ratio for COMPRESS BASIC';
COMMENT ON COLUMN T_COMPRESSION_ANALYSIS.OLTP_RATIO IS 'Compression ratio for COMPRESS ADVANCED (OLTP)';
COMMENT ON COLUMN T_COMPRESSION_ANALYSIS.ADV_LOW_RATIO IS 'Compression ratio for COMPRESS FOR QUERY LOW (requires license)';
COMMENT ON COLUMN T_COMPRESSION_ANALYSIS.ADV_HIGH_RATIO IS 'Compression ratio for COMPRESS FOR QUERY HIGH (requires license)';

-- Indexes for Performance
CREATE INDEX IDX_COMP_ANALYSIS_OBJECT ON T_COMPRESSION_ANALYSIS(
    OWNER, OBJECT_NAME
);

CREATE INDEX IDX_COMP_ANALYSIS_HOTNESS ON T_COMPRESSION_ANALYSIS(
    HOTNESS_SCORE
);

CREATE INDEX IDX_COMP_ANALYSIS_RUN ON T_COMPRESSION_ANALYSIS(
    ADVISOR_RUN_ID, ANALYSIS_DATE DESC
);

CREATE INDEX IDX_COMP_ANALYSIS_RECOMMENDATION ON T_COMPRESSION_ANALYSIS(
    ADVISABLE_COMPRESSION
);

CREATE BITMAP INDEX IDX_COMP_ANALYSIS_TYPE_BMP ON T_COMPRESSION_ANALYSIS(
    ADVISABLE_COMPRESSION
);

-- Removed: HOTNESS_CATEGORY is a virtual generated column and cannot be indexed in Oracle
-- Filtering by hotness_category should use HOTNESS_SCORE ranges via views instead

-- ----------------------------------------------------------------------------
-- Table: T_INDEX_COMPRESSION_ANALYSIS
-- Purpose: Index compression analysis results
-- ----------------------------------------------------------------------------
CREATE TABLE T_INDEX_COMPRESSION_ANALYSIS (
    -- Primary Key
    INDEX_ANALYSIS_ID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    -- Index Identification
    INDEX_OWNER             VARCHAR2(128) NOT NULL,
    INDEX_NAME              VARCHAR2(128) NOT NULL,
    TABLE_OWNER             VARCHAR2(128),
    TABLE_NAME              VARCHAR2(128),
    INDEX_TYPE              VARCHAR2(27),  -- NORMAL, BITMAP, FUNCTION-BASED
    UNIQUENESS              VARCHAR2(9),   -- UNIQUE, NONUNIQUE
    PARTITION_NAME          VARCHAR2(128),
    SUBPARTITION_NAME       VARCHAR2(128),
    -- Size Metrics
    INDEX_SIZE_BYTES        NUMBER,
    INDEX_SIZE_MB           NUMBER GENERATED ALWAYS AS (INDEX_SIZE_BYTES/1024/1024) VIRTUAL,
    LEAF_BLOCKS             NUMBER,
    DISTINCT_KEYS           NUMBER,
    CLUSTERING_FACTOR       NUMBER,
    -- Compression Ratios (Index Specific)
    PREFIX_COMPRESSION_RATIO    NUMBER(5,2),
    ADVANCED_LOW_RATIO          NUMBER(5,2),
    ADVANCED_HIGH_RATIO         NUMBER(5,2),
    -- Block counts
    BLKCNT_UNCMP_PREFIX     NUMBER,
    BLKCNT_CMP_PREFIX       NUMBER,
    BLKCNT_UNCMP_ADV_LOW    NUMBER,
    BLKCNT_CMP_ADV_LOW      NUMBER,
    BLKCNT_UNCMP_ADV_HIGH   NUMBER,
    BLKCNT_CMP_ADV_HIGH     NUMBER,
    -- Current State
    CURRENT_COMPRESSION     VARCHAR2(30),
    CURRENT_PREFIX_LENGTH   NUMBER,
    -- Access Patterns
    SCAN_COUNT              NUMBER,
    LOOKUP_COUNT            NUMBER,
    ACCESS_FREQUENCY        NUMBER,
    -- Recommendation
    ADVISABLE_COMPRESSION   VARCHAR2(30),
    RECOMMENDED_PREFIX_LENGTH NUMBER,
    RECOMMENDATION_REASON   VARCHAR2(4000),
    PROJECTED_SAVINGS_MB    NUMBER,
    -- Metadata
    ADVISOR_RUN_ID          NUMBER NOT NULL,
    ANALYSIS_DATE           DATE DEFAULT SYSDATE,
    ANALYSIS_TIMESTAMP      TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- Constraints
    CONSTRAINT PK_INDEX_COMPRESSION PRIMARY KEY (INDEX_ANALYSIS_ID),
    CONSTRAINT CHK_INDEX_ADVISABLE_COMPRESSION CHECK (
        ADVISABLE_COMPRESSION IN ('NONE', 'PREFIX', 'ADVANCED_LOW', 'ADVANCED_HIGH')
    )
);

COMMENT ON TABLE T_INDEX_COMPRESSION_ANALYSIS IS 'Index compression analysis results';

CREATE INDEX IDX_INDEX_COMP_NAME ON T_INDEX_COMPRESSION_ANALYSIS(
    INDEX_OWNER, INDEX_NAME
);

CREATE INDEX IDX_INDEX_COMP_TABLE ON T_INDEX_COMPRESSION_ANALYSIS(
    TABLE_OWNER, TABLE_NAME
);

-- ----------------------------------------------------------------------------
-- Table: T_LOB_COMPRESSION_ANALYSIS
-- Purpose: LOB (CLOB/BLOB) compression analysis results (SecureFiles only)
-- ----------------------------------------------------------------------------
CREATE TABLE T_LOB_COMPRESSION_ANALYSIS (
    -- Primary Key
    LOB_ANALYSIS_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    -- LOB Identification
    TABLE_OWNER             VARCHAR2(128) NOT NULL,
    TABLE_NAME              VARCHAR2(128) NOT NULL,
    COLUMN_NAME             VARCHAR2(128) NOT NULL,
    LOB_NAME                VARCHAR2(128),
    DATA_TYPE               VARCHAR2(106),  -- CLOB, BLOB, NCLOB
    SECUREFILE              VARCHAR2(3),    -- YES, NO
    PARTITION_NAME          VARCHAR2(128),
    SUBPARTITION_NAME       VARCHAR2(128),
    -- Size Metrics
    LOB_SIZE_BYTES          NUMBER,
    LOB_SIZE_MB             NUMBER GENERATED ALWAYS AS (LOB_SIZE_BYTES/1024/1024) VIRTUAL,
    NUM_LOBS                NUMBER,
    AVG_LOB_SIZE_KB         NUMBER,
    -- Current State
    CURRENT_COMPRESSION     VARCHAR2(30),
    CURRENT_DEDUPLICATION   VARCHAR2(3),
    CURRENT_ENCRYPTION      VARCHAR2(3),
    CHUNK_SIZE              NUMBER,
    -- Compression Ratios (SecureFiles)
    LOW_COMPRESSION_RATIO   NUMBER(5,2),
    MEDIUM_COMPRESSION_RATIO NUMBER(5,2),
    HIGH_COMPRESSION_RATIO  NUMBER(5,2),
    DEDUP_SAVINGS_PCT       NUMBER(5,2),
    -- Block counts
    BLKCNT_UNCMP_LOW        NUMBER,
    BLKCNT_CMP_LOW          NUMBER,
    BLKCNT_UNCMP_MEDIUM     NUMBER,
    BLKCNT_CMP_MEDIUM       NUMBER,
    BLKCNT_UNCMP_HIGH       NUMBER,
    BLKCNT_CMP_HIGH         NUMBER,
    -- Access Patterns
    READ_FREQUENCY          NUMBER,
    WRITE_FREQUENCY         NUMBER,
    READ_WRITE_RATIO        NUMBER(5,2),
    -- Recommendation
    ADVISABLE_COMPRESSION   VARCHAR2(30),
    ADVISABLE_DEDUP         VARCHAR2(3),
    RECOMMENDATION_REASON   VARCHAR2(4000),
    PROJECTED_SAVINGS_MB    NUMBER,
    RECOMMEND_SECUREFILE    VARCHAR2(1) DEFAULT 'N',
    -- Metadata
    ADVISOR_RUN_ID          NUMBER NOT NULL,
    ANALYSIS_DATE           DATE DEFAULT SYSDATE,
    ANALYSIS_TIMESTAMP      TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- Constraints
    CONSTRAINT PK_LOB_COMPRESSION PRIMARY KEY (LOB_ANALYSIS_ID),
    CONSTRAINT CHK_LOB_ADVISABLE_COMPRESSION CHECK (
        ADVISABLE_COMPRESSION IN ('NONE', 'LOW', 'MEDIUM', 'HIGH')
    ),
    CONSTRAINT CHK_LOB_SECUREFILE CHECK (SECUREFILE IN ('YES', 'NO'))
);

COMMENT ON TABLE T_LOB_COMPRESSION_ANALYSIS IS 'LOB compression analysis results (SecureFiles only)';

CREATE INDEX IDX_LOB_COMP_TABLE ON T_LOB_COMPRESSION_ANALYSIS(
    TABLE_OWNER, TABLE_NAME, COLUMN_NAME
);

-- ============================================================================
-- SECTION 3: EXECUTION HISTORY TABLES
-- ============================================================================

PROMPT
PROMPT Creating execution history tables...

-- ----------------------------------------------------------------------------
-- Table: T_COMPRESSION_HISTORY
-- Purpose: Complete audit trail of all compression execution operations
-- ----------------------------------------------------------------------------
CREATE TABLE T_COMPRESSION_HISTORY (
    -- Primary Key
    HISTORY_ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    EXECUTION_ID            NUMBER,  -- Unique execution batch identifier
    -- Object Identification
    OWNER                   VARCHAR2(128) NOT NULL,
    OBJECT_NAME             VARCHAR2(128) NOT NULL,
    OBJECT_TYPE             VARCHAR2(30) NOT NULL,
    PARTITION_NAME          VARCHAR2(128),
    SUBPARTITION_NAME       VARCHAR2(128),
    -- Compression Details
    COMPRESSION_TYPE_APPLIED VARCHAR2(30) NOT NULL,
    COMPRESSION_CLAUSE      VARCHAR2(200),  -- Actual DDL clause used
    EXECUTION_MODE          VARCHAR2(10),   -- ONLINE, OFFLINE
    PARALLEL_DEGREE         NUMBER,
    -- Size Metrics - Before
    ORIGINAL_SIZE_BYTES     NUMBER,
    ORIGINAL_SIZE_MB        NUMBER GENERATED ALWAYS AS (
        ORIGINAL_SIZE_BYTES/1024/1024
    ) VIRTUAL,
    ORIGINAL_BLOCKS         NUMBER,
    ORIGINAL_ROW_COUNT      NUMBER,
    -- Size Metrics - After
    COMPRESSED_SIZE_BYTES   NUMBER,
    COMPRESSED_SIZE_MB      NUMBER GENERATED ALWAYS AS (
        COMPRESSED_SIZE_BYTES/1024/1024
    ) VIRTUAL,
    COMPRESSED_BLOCKS       NUMBER,
    COMPRESSED_ROW_COUNT    NUMBER,
    -- Space Savings
    SPACE_SAVED_BYTES       NUMBER GENERATED ALWAYS AS (
        ORIGINAL_SIZE_BYTES - COMPRESSED_SIZE_BYTES
    ) VIRTUAL,
    SPACE_SAVED_MB          NUMBER GENERATED ALWAYS AS (
        (ORIGINAL_SIZE_BYTES - COMPRESSED_SIZE_BYTES)/1024/1024
    ) VIRTUAL,
    SPACE_SAVED_PCT         NUMBER(5,2) GENERATED ALWAYS AS (
        CASE WHEN ORIGINAL_SIZE_BYTES > 0 THEN
            ((ORIGINAL_SIZE_BYTES - COMPRESSED_SIZE_BYTES) / ORIGINAL_SIZE_BYTES) * 100
        ELSE 0 END
    ) VIRTUAL,
    -- Compression Ratio
    COMPRESSION_RATIO_ACHIEVED NUMBER(5,2),
    PREDICTED_RATIO            NUMBER(5,2),
    RATIO_VARIANCE             NUMBER(5,2) GENERATED ALWAYS AS (
        COMPRESSION_RATIO_ACHIEVED - PREDICTED_RATIO
    ) VIRTUAL,
    -- Timing Information
    START_TIME              TIMESTAMP DEFAULT SYSTIMESTAMP,
    END_TIME                TIMESTAMP,
    DURATION_SECONDS        NUMBER,
    DURATION_MINUTES        NUMBER GENERATED ALWAYS AS (
        DURATION_SECONDS / 60
    ) VIRTUAL,
    -- Execution Status
    OPERATION_STATUS        VARCHAR2(30) DEFAULT 'IN_PROGRESS',
    ERROR_CODE              NUMBER,
    ERROR_MESSAGE           VARCHAR2(4000),
    ERROR_BACKTRACE         VARCHAR2(4000),
    -- Performance Metrics
    CPU_TIME_SECONDS        NUMBER,
    IO_WAIT_SECONDS         NUMBER,
    TEMP_SPACE_MB           NUMBER,
    UNDO_SPACE_MB           NUMBER,
    -- Index Rebuild Information
    INDEXES_REBUILT_COUNT   NUMBER DEFAULT 0,
    INDEX_REBUILD_TIME_SEC  NUMBER,
    INDEX_REBUILD_STATUS    VARCHAR2(30),
    -- Validation
    VALIDATION_STATUS       VARCHAR2(30),
    DATA_INTEGRITY_CHECK    VARCHAR2(1) DEFAULT 'N',
    CHECKSUM_BEFORE         NUMBER,
    CHECKSUM_AFTER          NUMBER,
    -- Foreign Key
    ANALYSIS_ID             NUMBER,  -- Links to T_COMPRESSION_ANALYSIS
    -- Audit Information
    EXECUTED_BY             VARCHAR2(128) DEFAULT USER,
    EXECUTED_FROM_IP        VARCHAR2(45),
    EXECUTED_FROM_PROGRAM   VARCHAR2(64),
    -- Rollback Information
    ROLLBACK_POSSIBLE       VARCHAR2(1) DEFAULT 'Y',
    ROLLBACK_STATUS         VARCHAR2(30),
    ORIGINAL_DDL            CLOB,
    -- Constraints
    CONSTRAINT PK_COMPRESSION_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT CHK_HISTORY_OBJECT_TYPE CHECK (
        OBJECT_TYPE IN ('TABLE', 'INDEX', 'LOB', 'IOT', 'PARTITION', 'SUBPARTITION')
    ),
    CONSTRAINT CHK_HISTORY_COMPRESSION_TYPE CHECK (
        COMPRESSION_TYPE_APPLIED IN ('NONE', 'BASIC', 'OLTP', 'ADV_LOW', 'ADV_HIGH',
                                      'PREFIX', 'ADVANCED_LOW', 'ADVANCED_HIGH',
                                      'LOW', 'MEDIUM', 'HIGH')
    ),
    CONSTRAINT CHK_HISTORY_OPERATION_STATUS CHECK (
        OPERATION_STATUS IN ('IN_PROGRESS', 'SUCCESS', 'FAILED', 'ROLLED_BACK', 'PARTIAL_SUCCESS')
    ),
    CONSTRAINT CHK_HISTORY_EXECUTION_MODE CHECK (
        EXECUTION_MODE IN ('ONLINE', 'OFFLINE')
    ),
    CONSTRAINT CHK_HISTORY_DATA_INTEGRITY CHECK (
        DATA_INTEGRITY_CHECK IN ('Y', 'N')
    ),
    CONSTRAINT CHK_HISTORY_ROLLBACK_POSSIBLE CHECK (
        ROLLBACK_POSSIBLE IN ('Y', 'N')
    )
);

COMMENT ON TABLE T_COMPRESSION_HISTORY IS 'Complete audit trail of compression execution operations';

-- Indexes
CREATE UNIQUE INDEX UNQ_HISTORY_EXECUTION ON T_COMPRESSION_HISTORY(
    EXECUTION_ID
) WHERE EXECUTION_ID IS NOT NULL;

CREATE INDEX IDX_HISTORY_OBJECT ON T_COMPRESSION_HISTORY(
    OWNER, OBJECT_NAME, START_TIME DESC
);

CREATE INDEX IDX_HISTORY_STATUS ON T_COMPRESSION_HISTORY(
    OPERATION_STATUS, START_TIME DESC
);

CREATE INDEX IDX_HISTORY_COMPRESSION_TYPE ON T_COMPRESSION_HISTORY(
    COMPRESSION_TYPE_APPLIED, OPERATION_STATUS
);

CREATE BITMAP INDEX IDX_HISTORY_STATUS_BMP ON T_COMPRESSION_HISTORY(
    OPERATION_STATUS
);

-- ============================================================================
-- SECTION 4: ADVISOR RUN TRACKING
-- ============================================================================

PROMPT
PROMPT Creating advisor run tracking tables...

-- ----------------------------------------------------------------------------
-- Table: T_ADVISOR_RUN
-- Purpose: Track analysis execution sessions and metadata
-- ----------------------------------------------------------------------------
CREATE TABLE T_ADVISOR_RUN (
    -- Primary Key
    RUN_ID                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    -- Run Identification
    RUN_NAME                VARCHAR2(100),
    RUN_TYPE                VARCHAR2(30) NOT NULL,
    RUN_DESCRIPTION         VARCHAR2(500),
    -- Scope
    SCHEMA_FILTER           VARCHAR2(128),
    OBJECT_TYPE_FILTER      VARCHAR2(30),
    OBJECT_NAME_PATTERN     VARCHAR2(128),
    INCLUDE_PARTITIONS      VARCHAR2(1) DEFAULT 'N',
    -- Strategy
    STRATEGY_ID             NUMBER,
    STRATEGY_NAME           VARCHAR2(50),
    -- Configuration Parameters
    SAMPLE_SIZE             NUMBER DEFAULT 1000000,
    PARALLEL_DEGREE         NUMBER DEFAULT 4,
    ANALYSIS_MODE           VARCHAR2(20) DEFAULT 'FULL',
    -- Timing
    START_TIME              TIMESTAMP DEFAULT SYSTIMESTAMP,
    END_TIME                TIMESTAMP,
    DURATION_MINUTES        NUMBER,
    -- Status
    RUN_STATUS              VARCHAR2(30) DEFAULT 'RUNNING',
    ERROR_MESSAGE           VARCHAR2(4000),
    -- Statistics
    OBJECTS_ANALYZED        NUMBER DEFAULT 0,
    OBJECTS_SUCCEEDED       NUMBER DEFAULT 0,
    OBJECTS_FAILED          NUMBER DEFAULT 0,
    SUCCESS_RATE_PCT        NUMBER(5,2) GENERATED ALWAYS AS (
        CASE WHEN OBJECTS_ANALYZED > 0 THEN
            (OBJECTS_SUCCEEDED / OBJECTS_ANALYZED) * 100
        ELSE 0 END
    ) VIRTUAL,
    -- Space Analysis Summary
    TOTAL_SIZE_MB           NUMBER,
    COMPRESSIBLE_SIZE_MB    NUMBER,
    PROJECTED_SAVINGS_MB    NUMBER,
    PROJECTED_SAVINGS_PCT   NUMBER(5,2),
    -- Recommendations Summary
    RECOMMEND_NONE          NUMBER DEFAULT 0,
    RECOMMEND_BASIC         NUMBER DEFAULT 0,
    RECOMMEND_OLTP          NUMBER DEFAULT 0,
    RECOMMEND_ADV_LOW       NUMBER DEFAULT 0,
    RECOMMEND_ADV_HIGH      NUMBER DEFAULT 0,
    -- Performance Metrics
    CPU_TIME_SECONDS        NUMBER,
    ELAPSED_TIME_SECONDS    NUMBER,
    TEMP_SPACE_MB           NUMBER,
    -- Audit
    INITIATED_BY            VARCHAR2(128) DEFAULT USER,
    INITIATED_FROM          VARCHAR2(64),
    -- Constraints
    CONSTRAINT PK_ADVISOR_RUN PRIMARY KEY (RUN_ID),
    CONSTRAINT FK_RUN_STRATEGY FOREIGN KEY (STRATEGY_ID)
        REFERENCES T_COMPRESSION_STRATEGIES(STRATEGY_ID),
    CONSTRAINT CHK_RUN_TYPE CHECK (
        RUN_TYPE IN ('TABLES', 'INDEXES', 'LOBS', 'IOTS', 'ALL', 'CUSTOM')
    ),
    CONSTRAINT CHK_RUN_STATUS CHECK (
        RUN_STATUS IN ('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')
    ),
    CONSTRAINT CHK_ANALYSIS_MODE CHECK (
        ANALYSIS_MODE IN ('FULL', 'INCREMENTAL', 'QUICK')
    ),
    CONSTRAINT CHK_INCLUDE_PARTITIONS CHECK (
        INCLUDE_PARTITIONS IN ('Y', 'N')
    )
);

COMMENT ON TABLE T_ADVISOR_RUN IS 'Analysis execution sessions and metadata';

-- Indexes
CREATE INDEX IDX_ADVISOR_RUN_TIME ON T_ADVISOR_RUN(
    START_TIME DESC, RUN_STATUS
);

CREATE INDEX IDX_ADVISOR_RUN_SCHEMA ON T_ADVISOR_RUN(
    SCHEMA_FILTER, START_TIME DESC
);

CREATE BITMAP INDEX IDX_ADVISOR_RUN_STATUS_BMP ON T_ADVISOR_RUN(
    RUN_STATUS
);

-- ============================================================================
-- SECTION 5: FOREIGN KEY CONSTRAINTS (Deferred for circular dependencies)
-- ============================================================================

PROMPT
PROMPT Adding foreign key constraints...

ALTER TABLE T_COMPRESSION_ANALYSIS
ADD CONSTRAINT FK_ANALYSIS_RUN
FOREIGN KEY (ADVISOR_RUN_ID) REFERENCES T_ADVISOR_RUN(RUN_ID)
ON DELETE CASCADE;

ALTER TABLE T_INDEX_COMPRESSION_ANALYSIS
ADD CONSTRAINT FK_INDEX_ANALYSIS_RUN
FOREIGN KEY (ADVISOR_RUN_ID) REFERENCES T_ADVISOR_RUN(RUN_ID)
ON DELETE CASCADE;

ALTER TABLE T_LOB_COMPRESSION_ANALYSIS
ADD CONSTRAINT FK_LOB_ANALYSIS_RUN
FOREIGN KEY (ADVISOR_RUN_ID) REFERENCES T_ADVISOR_RUN(RUN_ID)
ON DELETE CASCADE;

ALTER TABLE T_COMPRESSION_HISTORY
ADD CONSTRAINT FK_HISTORY_ANALYSIS
FOREIGN KEY (ANALYSIS_ID) REFERENCES T_COMPRESSION_ANALYSIS(ANALYSIS_ID)
ON DELETE SET NULL;

-- ============================================================================
-- SECTION 6: SEQUENCES
-- ============================================================================

PROMPT
PROMPT Creating sequences...

CREATE SEQUENCE SEQ_EXECUTION_ID
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

COMMENT ON SEQUENCE SEQ_EXECUTION_ID IS 'Unique identifier for compression execution batches';

-- ============================================================================
-- SECTION 7: DEFAULT DATA
-- ============================================================================

PROMPT
PROMPT Inserting default strategy configurations...

-- Default Strategy: BALANCED_PRODUCTION
INSERT INTO T_COMPRESSION_STRATEGIES (
    STRATEGY_NAME,
    DESCRIPTION,
    CATEGORY,
    HOTNESS_THRESHOLD_HOT,
    HOTNESS_THRESHOLD_WARM,
    HOTNESS_THRESHOLD_COOL,
    DML_THRESHOLD_HIGH,
    DML_THRESHOLD_MEDIUM,
    DML_THRESHOLD_LOW,
    SIZE_THRESHOLD_LARGE_GB,
    SIZE_THRESHOLD_MEDIUM_GB,
    SIZE_THRESHOLD_SMALL_GB,
    MIN_COMPRESSION_RATIO,
    MIN_SPACE_SAVINGS_MB,
    ACTIVE_FLAG,
    IS_DEFAULT,
    PRIORITY
) VALUES (
    'BALANCED_PRODUCTION',
    'Balanced compression strategy for general production workloads (Oracle 23c Free)',
    'BALANCED',
    75,    -- HOT threshold
    50,    -- WARM threshold
    25,    -- COOL threshold
    5000,  -- HIGH DML
    500,   -- MEDIUM DML
    50,    -- LOW DML
    50,    -- Large GB
    5,     -- Medium GB
    0.5,   -- Small GB
    1.5,   -- Min ratio
    100,   -- Min savings MB
    'Y',
    'Y',
    100
);

-- Performance Strategy: HIGH_PERFORMANCE
INSERT INTO T_COMPRESSION_STRATEGIES (
    STRATEGY_NAME,
    DESCRIPTION,
    CATEGORY,
    HOTNESS_THRESHOLD_HOT,
    HOTNESS_THRESHOLD_WARM,
    HOTNESS_THRESHOLD_COOL,
    DML_THRESHOLD_HIGH,
    DML_THRESHOLD_MEDIUM,
    DML_THRESHOLD_LOW,
    MIN_COMPRESSION_RATIO,
    MIN_SPACE_SAVINGS_MB,
    ACTIVE_FLAG,
    IS_DEFAULT,
    PRIORITY
) VALUES (
    'HIGH_PERFORMANCE',
    'Minimal compression for high-performance OLTP systems',
    'PERFORMANCE',
    85,    -- Higher HOT threshold
    65,    -- Higher WARM threshold
    35,    -- Higher COOL threshold
    10000,
    1000,
    100,
    2.0,   -- Higher minimum ratio required
    200,   -- Higher minimum savings required
    'Y',
    'N',
    90
);

-- Space Optimization Strategy: MAXIMUM_COMPRESSION
INSERT INTO T_COMPRESSION_STRATEGIES (
    STRATEGY_NAME,
    DESCRIPTION,
    CATEGORY,
    HOTNESS_THRESHOLD_HOT,
    HOTNESS_THRESHOLD_WARM,
    HOTNESS_THRESHOLD_COOL,
    DML_THRESHOLD_HIGH,
    DML_THRESHOLD_MEDIUM,
    DML_THRESHOLD_LOW,
    MIN_COMPRESSION_RATIO,
    MIN_SPACE_SAVINGS_MB,
    ACTIVE_FLAG,
    IS_DEFAULT,
    PRIORITY
) VALUES (
    'MAXIMUM_COMPRESSION',
    'Aggressive compression for data warehouse and archival systems',
    'SPACE',
    65,    -- Lower HOT threshold
    40,    -- Lower WARM threshold
    15,    -- Lower COOL threshold
    1000,
    100,
    10,
    1.2,   -- Lower minimum ratio (more aggressive)
    50,    -- Lower minimum savings (compress more)
    'Y',
    'N',
    80
);

COMMIT;

-- ============================================================================
-- SECTION 8: STATISTICS COLLECTION PREFERENCES
-- ============================================================================

PROMPT
PROMPT Setting statistics collection preferences...

BEGIN
    -- Set incremental statistics for partitioned tables (if any)
    FOR t IN (
        SELECT table_name
        FROM user_tables
        WHERE table_name IN (
            'T_COMPRESSION_ANALYSIS',
            'T_COMPRESSION_HISTORY'
        )
    ) LOOP
        DBMS_STATS.SET_TABLE_PREFS(
            ownname => USER,
            tabname => t.table_name,
            pname   => 'INCREMENTAL',
            pvalue  => 'TRUE'
        );

        DBMS_STATS.SET_TABLE_PREFS(
            ownname => USER,
            tabname => t.table_name,
            pname   => 'PUBLISH',
            pvalue  => 'TRUE'
        );

        DBMS_STATS.SET_TABLE_PREFS(
            ownname => USER,
            tabname => t.table_name,
            pname   => 'STALE_PERCENT',
            pvalue  => '10'
        );
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Statistics preferences configured successfully');
END;
/

-- ============================================================================
-- SECTION 9: VERIFICATION
-- ============================================================================

PROMPT
PROMPT ================================================================================
PROMPT Schema Creation Summary
PROMPT ================================================================================

SELECT
    object_type,
    COUNT(*) AS object_count,
    SUM(CASE WHEN status = 'VALID' THEN 1 ELSE 0 END) AS valid_count,
    SUM(CASE WHEN status != 'VALID' THEN 1 ELSE 0 END) AS invalid_count
FROM user_objects
WHERE object_name LIKE 'T_%COMPRESS%'
   OR object_name LIKE 'SEQ_%'
   OR object_name LIKE 'IDX_%COMP%'
   OR object_name LIKE 'UNQ_%'
GROUP BY object_type
ORDER BY object_type;

PROMPT
PROMPT Table row counts:
SELECT 'T_COMPRESSION_STRATEGIES' AS table_name, COUNT(*) AS row_count FROM T_COMPRESSION_STRATEGIES
UNION ALL
SELECT 'T_STRATEGY_RULES', COUNT(*) FROM T_STRATEGY_RULES
UNION ALL
SELECT 'T_COMPRESSION_ANALYSIS', COUNT(*) FROM T_COMPRESSION_ANALYSIS
UNION ALL
SELECT 'T_INDEX_COMPRESSION_ANALYSIS', COUNT(*) FROM T_INDEX_COMPRESSION_ANALYSIS
UNION ALL
SELECT 'T_LOB_COMPRESSION_ANALYSIS', COUNT(*) FROM T_LOB_COMPRESSION_ANALYSIS
UNION ALL
SELECT 'T_COMPRESSION_HISTORY', COUNT(*) FROM T_COMPRESSION_HISTORY
UNION ALL
SELECT 'T_ADVISOR_RUN', COUNT(*) FROM T_ADVISOR_RUN;

PROMPT
PROMPT ================================================================================
PROMPT Schema creation completed successfully!
PROMPT ================================================================================
PROMPT
PROMPT Next Steps:
PROMPT 1. Review the created objects above
PROMPT 2. Install PL/SQL packages: @02_packages.sql
PROMPT 3. Create reporting views: @03_views.sql
PROMPT 4. Run test suite: @04_test.sql
PROMPT ================================================================================

SET ECHO OFF
