-- Test script to verify HCC compression types work

PROMPT Testing HCC Compression Type Inserts
PROMPT =====================================

-- Test 1: Insert a QUERY HIGH rule
PROMPT Testing QUERY HIGH...
BEGIN
  INSERT INTO T_STRATEGY_RULES (
    RULE_ID, STRATEGY_ID, OBJECT_TYPE, HOTNESS_MIN, HOTNESS_MAX,
    MIN_WRITE_RATIO, MAX_WRITE_RATIO, COMPRESSION_TYPE, PRIORITY, RULE_DESCRIPTION
  ) VALUES (
    SEQ_STRATEGY_RULES.NEXTVAL, 1, 'INDEX', 60, 100, 0, 1.0,
    'QUERY HIGH', 99, 'Test QUERY HIGH'
  );
  DBMS_OUTPUT.PUT_LINE('✓ QUERY HIGH inserted successfully');
  ROLLBACK;
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('✗ QUERY HIGH failed: ' || SQLERRM);
  ROLLBACK;
END;
/

-- Test 2: Insert a QUERY LOW rule
PROMPT Testing QUERY LOW...
BEGIN
  INSERT INTO T_STRATEGY_RULES (
    RULE_ID, STRATEGY_ID, OBJECT_TYPE, HOTNESS_MIN, HOTNESS_MAX,
    MIN_WRITE_RATIO, MAX_WRITE_RATIO, COMPRESSION_TYPE, PRIORITY, RULE_DESCRIPTION
  ) VALUES (
    SEQ_STRATEGY_RULES.NEXTVAL, 1, 'INDEX', 30, 60, 0, 1.0,
    'QUERY LOW', 99, 'Test QUERY LOW'
  );
  DBMS_OUTPUT.PUT_LINE('✓ QUERY LOW inserted successfully');
  ROLLBACK;
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('✗ QUERY LOW failed: ' || SQLERRM);
  ROLLBACK;
END;
/

-- Test 3: Insert ARCHIVE HIGH
PROMPT Testing ARCHIVE HIGH...
BEGIN
  INSERT INTO T_STRATEGY_RULES (
    RULE_ID, STRATEGY_ID, OBJECT_TYPE, HOTNESS_MIN, HOTNESS_MAX,
    MIN_WRITE_RATIO, MAX_WRITE_RATIO, COMPRESSION_TYPE, PRIORITY, RULE_DESCRIPTION
  ) VALUES (
    SEQ_STRATEGY_RULES.NEXTVAL, 2, 'LOB', 0, 100, 0, 1.0,
    'NONE', 99, 'Test LOB NONE'
  );
  DBMS_OUTPUT.PUT_LINE('✓ LOB NONE inserted successfully');
  ROLLBACK;
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('✗ LOB NONE failed: ' || SQLERRM);
  ROLLBACK;
END;
/

PROMPT
PROMPT Current constraint definition:
SELECT SEARCH_CONDITION FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'CHK_RULE_COMPRESSION_TYPE';
